export const iteration4AuditActions = [
  "create",
  "update",
  "submit",
  "approve",
  "reject",
  "lock",
  "unlock",
  "export",
] as const;

export const auditLogActions = [
  ...iteration4AuditActions,
  "accepted",
  "approved",
  "bill_import",
  "calculate",
  "cancel",
  "completed",
  "copy_from",
  "created",
  "delete",
  "draft",
  "expired",
  "failed",
  "feedback_persisted",
  "generated",
  "ignored",
  "knowledge_entry.create",
  "manual_pricing",
  "memory_entry.create",
  "queued",
  "recalculate",
  "rejected",
  "retried",
  "settled",
  "submitted",
  "unlock_request",
  "update_pricing_defaults",
  "update_status",
  "withdraw",
] as const;

export type AuditLogAction = (typeof auditLogActions)[number];
