export const RESOURCE_DEFINITIONS = [
  {
    name: "project-summary",
    uri: "/v1/resources/project-summary",
    mode: "read",
    description: "Aggregate pricing summary for a project scope",
    parameters: ["projectId", "billVersionId?", "stageCode?", "disciplineCode?"],
  },
  {
    name: "summary-details",
    uri: "/v1/resources/summary-details",
    mode: "read",
    description: "Detailed variance breakdown for a project scope",
    parameters: [
      "projectId",
      "billVersionId?",
      "stageCode?",
      "disciplineCode?",
      "limit?",
    ],
  },
  {
    name: "jobs-summary",
    uri: "/v1/resources/jobs-summary",
    mode: "read",
    description: "Background job list and status summary",
    parameters: ["projectId?", "requestedBy?", "jobType?", "status?", "limit?"],
  },
  {
    name: "project-context",
    uri: "/v1/resources/project-context",
    mode: "read",
    description: "Combined project summary, jobs summary, knowledge summary, and optional job snapshot",
    parameters: [
      "projectId",
      "billVersionId?",
      "stageCode?",
      "disciplineCode?",
      "jobsRequestedBy?",
      "jobsStatus?",
      "jobsLimit?",
      "jobId?",
    ],
  },
  {
    name: "job-status",
    uri: "/v1/resources/job-status",
    mode: "read",
    description: "Single background job status snapshot",
    parameters: ["jobId"],
  },
  {
    name: "knowledge-extraction-result",
    uri: "/v1/resources/knowledge-extraction-result",
    mode: "read",
    description: "Knowledge extraction job result snapshot",
    parameters: ["jobId"],
  },
  {
    name: "knowledge-extraction-history",
    uri: "/v1/resources/knowledge-extraction-history",
    mode: "read",
    description: "Recent knowledge extraction jobs for a project",
    parameters: ["projectId", "requestedBy?", "status?", "limit?"],
  },
  {
    name: "review-summary",
    uri: "/v1/resources/review-summary",
    mode: "read",
    description: "Review submissions list and action summary",
    parameters: ["projectId", "billVersionId?", "stageCode?", "disciplineCode?", "status?"],
  },
  {
    name: "process-document-summary",
    uri: "/v1/resources/process-document-summary",
    mode: "read",
    description: "Process document list and status summary",
    parameters: ["projectId", "stageCode?", "disciplineCode?", "documentType?", "status?"],
  },
  {
    name: "report-export-status",
    uri: "/v1/resources/report-export-status",
    mode: "read",
    description: "Report export task status and download readiness",
    parameters: ["taskId"],
  },
  {
    name: "import-failure-context",
    uri: "/v1/resources/import-failure-context",
    mode: "read",
    description: "Current import failure scope, filtered failed items, and retry-snapshot readiness",
    parameters: [
      "projectId",
      "importTaskId?",
      "failureReason?",
      "failureResourceType?",
      "failureAction?",
    ],
  },
] as const;

export const TOOL_DEFINITIONS = [
  {
    name: "recalculate-project",
    uri: "/v1/tools/recalculate-project",
    mode: "invoke",
    description: "Queue recalculation for a project scope",
    parameters: ["projectId", "stageCode?", "disciplineCode?", "priceVersionId?", "feeTemplateId?"],
  },
  {
    name: "export-summary-report",
    uri: "/v1/tools/export-summary-report",
    mode: "invoke",
    description: "Queue an export task for summary or variance report output",
    parameters: ["projectId", "reportType", "stageCode?", "disciplineCode?"],
  },
  {
    name: "extract-knowledge",
    uri: "/v1/tools/extract-knowledge",
    mode: "invoke",
    description: "Queue AI knowledge extraction for structured project events",
    parameters: ["projectId", "source", "events"],
  },
  {
    name: "preview-knowledge-extraction",
    uri: "/v1/tools/preview-knowledge-extraction",
    mode: "invoke",
    description: "Run synchronous AI knowledge extraction preview for structured project events",
    parameters: ["source", "events"],
  },
  {
    name: "extract-knowledge-from-audit",
    uri: "/v1/tools/extract-knowledge-from-audit",
    mode: "invoke",
    description: "Queue AI knowledge extraction from project audit logs",
    parameters: [
      "projectId",
      "source?",
      "resourceType?",
      "resourceId?",
      "resourceIdPrefix?",
      "action?",
      "operatorId?",
      "createdFrom?",
      "createdTo?",
      "limit?",
    ],
  },
  {
    name: "retry-import-failure-scope",
    uri: "/v1/tools/retry-import-failure-scope",
    mode: "invoke",
    description: "Retry a failed knowledge-extraction job for the current import failure scope",
    parameters: ["jobId", "failureReason?", "failureResourceType?", "failureAction?"],
  },
  {
    name: "decide-review",
    uri: "/v1/tools/decide-review",
    mode: "invoke",
    description: "Approve, reject, or cancel a review submission",
    parameters: ["projectId", "reviewSubmissionId", "action", "comment?", "reason?"],
  },
  {
    name: "update-process-document-status",
    uri: "/v1/tools/update-process-document-status",
    mode: "invoke",
    description: "Submit, approve, or reject a process document",
    parameters: ["projectId", "documentId", "status", "comment?"],
  },
] as const;
